#!/usr/bin/python3
"""Module that factorise all numbers it should into a product of two smaller numbers."""
from sys import argv


def factorize(value):
    """"print out a simple decomposition of an integer > 1"""
    i = 2

    if value < 2:
        return
    print()
    print(value, "<- value-bef")
    while value % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(value, value / i, i))
    print(value, "<- value-aft")
    print()

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readliline()

        while line != "":
            value = int(line.split('\n')[0])
            factorise(value)
            line = file.readliline()
except:
    pass
